### ISSUE TITLE
Hard-coded launch path for newly-installed release?

### ISSUE THREAD

**Issue by interstateone** [mxcl/AppUpdater#1]
I'll admit I haven't tried this yet but at a glance on GitHub this line that launches the new release looks like it might be hard-coded for a specific app. Should this be something like `installedAppBundle.executablePath` instead?

```swift
proc.launchPath = installedAppBundle.Contents.MacOS.Cake.string
```
https://github.com/mxcl/AppUpdater/blob/master/AppUpdater.swift#L95

**Comment by mxcl** [comment]
My bad, I pulled this from another project and thought I’d caught all such things.

I guess I need to figure out how to write tests for this thing.

**Comment by interstateone** [comment]
No worries, thanks for releasing this!
