### ISSUE TITLE
MacOS App, Assets Name error

### ISSUE THREAD

**Issue by Aayush9029** [mxcl/AppUpdater#10]
- I am assuming the binary located at is MyAppName.app/Contents/MacOS/AppName

- I then renamed it to Reponame-1.0.0

- Then I published it.

My Repo is
> RifiApp

Here's my Release Page
> https://github.com/Aayush9029/RifiApp/releases/tag/1.0.0

---
Here's the error:
```PromiseKit:cauterized-error: Bad input was provided to a PromiseKit function```

**Assets** must be named
Are **Assets** the binary in this case or something else?

Other Information:
I am running the build through Xcode. Version 12.5 (12E262)
App is made using Coca, supported version MacOS 11.0

The App was Signed with a Developer ID cert, notarized.

Any help would be much appreciated.

**Comment by mxcl** [comment]
Did you figure it out? Happy to help, have time now.

**Comment by Aayush9029** [comment]
Ended up making a custom one.

Thanks!
