### ISSUE TITLE
Xcode projects?

### ISSUE THREAD

**Issue by pixlwave** [mxcl/AppUpdater#7]
At the risk of sounding stupid, is it possible to use this with an Xcode project? I tried cloning the repo and building which gave me AppUpdater.swiftmodule, but I'm not sure how I'd use that from Xcode?

**Comment by mxcl** [comment]
You can drag and drop the single swift file into your project.

If you want package management, Carthage will work, but you will still need to drag and drop the source file from the Carthage checkout. CocoaPods can do this too, but it will not automatically update. You could even use SwiftPM with the same source-dragging requirement, it will keep the dependency up-to-date too like Carthage.

Finally I offer Cake that you can use for this too, but I expect it is too exotic for your needs.

**Comment by pixlwave** [comment]
Thanks for the reply 😃

> If you want package management

This is how I should have framed my original question 🤦🏻‍♂️. I was pretty excited to see that AppUpdater is a single source file project, and was about to drop it into my project (my favourite method for using third party code) until I noticed it had dependencies. A better question would have been "Is there an easy way to integrate AppUpdater along with its dependencies into an Xcode project?"

Interestingly after your mention of using Carthage I checked your [Path.swift](https://github.com/mxcl/Path.swift) for Carthage support and found https://github.com/Carthage/Carthage/pull/1945, which is the kind of thing I was thinking of. So until then, I'll fetch with SPM and drag all the dependencies in that way. Although maybe WWDC will bring us SPM integration with Xcode anyway 🤞🏻

> Finally I offer Cake that you can use for this too, but I expect it is too exotic for your needs.

Damn this looks interesting, I'm going to have to have a tinker with it!

**Comment by mxcl** [comment]
Sorry I forgot there were dependencies to this package. So yeah, SwiftPM is probably your only reasonable choice.

It *is* possible to generate an xcodeproj from a `Package.swift` for your app’s deps and use that from your app’s xcodeproj. It's not recommended though, since it's a bit fiddly.

**Comment by pixlwave** [comment]
I hadn't thought about using the generated xcodeproj. Just tried and it works a treat! Thanks 🙏
